### ISSUE TITLE
Get some form of merge restriction

### ISSUE THREAD

**Issue by sims1253** [coala/cEPs#50]
Would be nice to make it impossible to merge cEPs with only one ack

**Comment by sils** [comment]
there's services FWIW and on long term we could of course let gitmate require two acks

**Comment by jayvdb** [comment]
This can now be done using GitHub branch protection, which can require multiple approvers.

Also we can restrict who can approve, which requires a [CODEOWNERS file]( help.github.com/articles/about-codeowners)

Lets start by letting all developers be approvers, and requiring two approvers.

Then we still have gitmate ack's which can only be done by a maintainer prior to merge.  So that is a third approver if the first two were not a maintainer.
